// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bill struct {
	ID       string    `json:"ID"`
	Currency *Currency `json:"currency"`
	Value    *float64  `json:"value"`
}

type Currency struct {
	Name string `json:"name"`
}

type Exchange struct {
	ID           *string                `json:"ID"`
	FromBill     *Bill                  `json:"fromBill"`
	ToBill       *Bill                  `json:"toBill"`
	ExchangeRate *float64               `json:"exchangeRate"`
	People       map[string]interface{} `json:"people"`
	PersonOnly   *ExchangePair          `json:"personOnly"`
}

type ExchangePair struct {
	ID        *string  `json:"ID"`
	Owner     *Person  `json:"owner"`
	FromValue *float64 `json:"fromValue"`
	ToValue   *float64 `json:"toValue"`
}

type Person struct {
	ID string `json:"ID"`
}
