// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bill interface {
	IsBill()
}

type Currency struct {
	Name string `json:"name"`
}

type Exchange struct {
	ID               *string      `json:"ID"`
	ExchangeFromBill *TotalBill   `json:"exchangeFromBill"`
	ExchangeToBill   *ForeignBill `json:"exchangeToBill"`
	ExchangeRate     *float64     `json:"exchangeRate"`
}

type ForeignBill struct {
	ID       string    `json:"ID"`
	Currency *Currency `json:"currency"`
	Value    *float64  `json:"value"`
}

func (ForeignBill) IsBill() {}

type Person struct {
	ID   string        `json:"ID"`
	Bill *PersonalBill `json:"bill"`
}

type PersonalBill struct {
	ID       string    `json:"ID"`
	Currency *Currency `json:"currency"`
	Value    *float64  `json:"value"`
}

func (PersonalBill) IsBill() {}

type TotalBill struct {
	ID       string    `json:"ID"`
	Currency *Currency `json:"currency"`
	Value    *float64  `json:"value"`
	People   []*Person `json:"people"`
}

func (TotalBill) IsBill() {}
